### ISSUE TITLE
CustomResourceDefinition.apiextensions.k8s.io "scaledjobs.keda.sh" is invalid: metadata.annotations: Too long: must have at most 262144 bytes

### ISSUE THREAD

**Issue by teebu** [kedacore/charts#580] opened 2023-12-01 19:52 UTC
I should state that is **not a bug** and probably not the right place for this.

NOTE: *this issue is related to ArgoCD and how charts get applied - but why does it have to be so large?*
https://github.com/argoproj/argo-cd/issues/820

The scaledjobs.keda.sh seems to be reaching some size limits. I'm not sure who or what sets those limits.

I'm going from v2.7.0 where the crd has roughly 4000 lines
https://github.com/kedacore/charts/blob/v2.7.0/keda/templates/03-crd-scaledjobs.keda.sh.yaml
to 2.12.0 which has over 8000 lines and almost a megabyte is size.
https://github.com/kedacore/charts/blob/v2.12.0/keda/templates/crds/crd-scaledjobs.yaml

## Expected Behavior

I expect it to sync and work without issues.

## Actual Behavior

```
SyncError
Failed sync attempt to 89b6e62d3659e6d9902cca2d1ef6625cff396e40: one or more objects failed to apply, reason: CustomResourceDefinition.apiextensions.k8s.io "scaledjobs.keda.sh" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

## Steps to Reproduce the Problem

  1. Using the template files with Argocd
  2. Sync the chart
  3.

## Specifications

  - **KEDA Version:** 2.12.0 
  - **Platform & Version:** *Please elaborate*
  - **Kubernetes Version:** 1.26.6 on Azure
  - **Scaler(s):** *Please elaborate*

**Comment by tomkerkhove** [comment] 2023-12-03 22:15
It looks like your annotations are too big on the scaled object: `metadata.annotations: Too long: must have at most 262144 bytes`

**Comment by zroubalik** [comment] 2023-12-04 14:11
Duplicate of https://github.com/kedacore/keda/issues/5245

Use server side apply.

**Closed by zroubalik** 2023-12-04 14:11 UTC
Labels: bug
