### ISSUE TITLE
Error Deploying 2.9.2 `unknown flag --cert-dir`

### ISSUE THREAD

**Issue by pinkfloydx33** [kedacore/charts#369] opened 2023-01-16 21:40 UTC
My FluxCD managed KEDA installation just attempted to upgrade from 2.9.1 to 2.9.2. The operation failed, "timeout waiting for the condition". An inspection of the newly created pods show a Crash Backoff Loop on `keda-operator`. Inspecting the logs of the new pod show:

```
unknown flag: --cert-dir
Usage of /keda:
      --disable-compression                   Disable response compression for k8s restAPI in client-go.  (default true)
      --health-probe-bind-address string      The address the probe endpoint binds to. (default ":8081")
      --kube-api-burst int                    Set the burst for throttling requests sent to the apiserver (default 30)
      --kube-api-qps float32                  Set the QPS rate for throttling requests sent to the apiserver (default 20)
      --kubeconfig string                     Paths to a kubeconfig. Only required if out-of-cluster.
      --leader-elect                          Enable leader election for controller manager. Enabling this will ensure there is only one active controller manager.
      --metrics-bind-address string           The address the metric endpoint binds to. (default ":8080")
      --metrics-service-bind-address string   The address the gRPRC Metrics Service endpoint binds to. (default ":9666")
      --zap-devel                             Development Mode defaults(encoder=consoleEncoder,logLevel=Debug,stackTraceLevel=Warn). Production Mode defaults(encoder=jsonEncoder,logLevel=Info,stackTraceLevel=Error)
      --zap-encoder encoder                   Zap log encoding (one of 'json' or 'console') (default )
      --zap-log-level level                   Zap Level to configure the verbosity of logging. Can be one of 'debug', 'info', 'error', or any integer value > 0 which corresponds to custom debug levels of increasing verbosity (default )
      --zap-stacktrace-level level            Zap Level at and above which stacktraces are captured (one of 'info', 'error', 'panic').
      --zap-time-encoding time-encoding       Zap time encoding (one of 'epoch', 'millis', 'nano', 'iso8601', 'rfc3339' or 'rfc3339nano'). Defaults to 'epoch'. (default )
unknown flag: --cert-dir
```

Additionally, the metrics operator is stuck trying to create the container. Kubernetes events show:

> 85s         Warning   FailedMount   pod/keda-operator-metrics-apiserver-7cfc477b54-stwxg   MountVolume.SetUp failed for volume "certificates" : secret "kedaorg-certs" not found
> 6m38s       Warning   FailedMount   pod/keda-operator-metrics-apiserver-7cfc477b54-stwxg   Unable to attach or mount volumes: unmounted volumes=[certificates], unattached volumes=[azure-identity-token certificates kube-api-access-8btmg]: timed out waiting for the condition

## Expected Behavior
Keda installs successfully

## Actual Behavior
Helm upgrade fails and Keda does not start

## Steps to Reproduce the Problem

  1. Upgrade from 2.9.1 to 2.9.2

## Specifications

  - **KEDA Version:** 2.9.2
  - **Platform & Version:** AKS, Flux managed Keda
  - **Kubernetes Version:** 1.25.4
  - **Scaler(s):** N/A

Image of the newly created (and failing container) is `ghcr.io/kedacore/keda:2.9.2`

**Comment by JorTurFer** [comment] 2023-01-16 21:55
Sorry, we have introduced a wrong chart in the index by error, and even we have reverted the change in a few minutes, it looks like your system has been faster than we. 
I apologize and we are releasing a new chart version right now, it should be fixed during next minutes

**Comment by pinkfloydx33** [comment] 2023-01-16 22:05
It's cool. It's only my dev environment that's configured to auto-upgrade Keda (within the minor version) anyways. 

I imagine the issue comes from the version mismatch with the chart and app? Stinks not having the versions in sync

**Comment by JorTurFer** [comment] 2023-01-16 22:07
The new chart has been release, check it please and let

**Comment by zroubalik** [comment] 2023-01-16 22:09
> I imagine the issue comes from the version mismatch with the chart and app? Stinks not having the versions in sync

Sometimes we need to update features present on charts but not in the core, so the versions don't match 🤷‍♂️ But that shouldn't be a problem.

This problem was just caused by human error (me 😄) .

**Comment by pinkfloydx33** [comment] 2023-01-16 22:12
Just to double check -- chart 2.9.3 has installed but the webhooks, certs, etc. are not part of the chart. Is this correct?

**Comment by JorTurFer** [comment] 2023-01-16 22:13
no they aren't, they are part of the next minor release (that's why they are already in main)

**Comment by pinkfloydx33** [comment] 2023-01-16 22:14
Ok just making sure =p. Everything appears to be good then! Thanks for prompt action.

**Comment by JorTurFer** [comment] 2023-01-16 22:17
Nice to read that the issue is solved! ❤️ 
Thanks for the early report too, because we overrode the v2.9.2 but we didn't think in auto-updated systems, which could be affected. Tomorrow the impact (and the amount of issues) would be crazy xD
Luckily, it's already solved :)

**Closed by JorTurFer** 2023-01-16 22:17 UTC
Labels: bug
